# SOPS configuration for age encryption
# Replace the age key below with your own public key
# Generate a new key with: age-keygen -o ~/.config/sops/age/keys.txt
# Then get your public key with: age-keygen -y ~/.config/sops/age/keys.txt

creation_rules:
  - path_regex: .*\.enc\.yaml$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
